production:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: <%= ENV['MONGO_URL'] %>

# local
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: <%= ENV['MONGO_URL'] %>

test:
  sessions:
    default:
      database: motion_bank_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
